### ISSUE TITLE
Get XUnit working and make all tests pass

### ISSUE THREAD

**Issue by GGAlanSmithee** [koopla/NodeServices#5]
As mentioned by @johnnyoshika in #4 we'll need to get test passing.

* [ ] Get XUnit working
* [ ] Make all tests pass

**Comment by johnnyoshika** [comment]
Thanks for creating this, @GGAlanSmithee!

**Comment by johnnyoshika** [comment]
@GGAlanSmithee Do you have any update on this? Please note that the test project no longer compiles in the solution after this PR: https://github.com/koopla/NodeServices/pull/6

**Comment by GGAlanSmithee** [comment]
@johnnyoshika sorry no update just yet. I started working on it, but other work got in the way. Atm, I'm a bit comprehensive to put hours into this since https://github.com/aspnet/AspNetCore/issues/12890#issuecomment-554624959. Can you please clarify the rationale for this project to be maintained further? If you have time ofc - I would do it myself but been too busy lately. Thanks!

**Comment by johnnyoshika** [comment]
@GGAlanSmithee We want to offer existing users of INodeServices a non-deprecated drop-in replacement for it. My plan is to continue fixing bugs and accepting PRs for that and continuing to ensure that this project is compatible with future .Net versions.

I hope that makes sense.

If you're too busy to tackle this on your own, would you be open to a quick screen sharing jam session? If I can get unstuck on my problem, I should be able to finish the rest.
